# Form implementation generated from reading ui file 'autorization.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AuthWindow(object):
    def setupUi(self, AuthWindow):
        AuthWindow.setObjectName("AuthWindow")
        AuthWindow.setEnabled(True)
        AuthWindow.resize(375, 327)
        AuthWindow.setMinimumSize(QtCore.QSize(375, 327))
        AuthWindow.setMaximumSize(QtCore.QSize(375, 327))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/ProgrammIcon.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        AuthWindow.setWindowIcon(icon)
        AuthWindow.setSizeGripEnabled(False)
        self.auth_button = QtWidgets.QPushButton(parent=AuthWindow)
        self.auth_button.setGeometry(QtCore.QRect(10, 280, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.auth_button.setFont(font)
        self.auth_button.setObjectName("auth_button")
        self.exit_button = QtWidgets.QPushButton(parent=AuthWindow)
        self.exit_button.setGeometry(QtCore.QRect(280, 280, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.exit_button.setFont(font)
        self.exit_button.setObjectName("exit_button")
        self.authorization_label = QtWidgets.QLabel(parent=AuthWindow)
        self.authorization_label.setGeometry(QtCore.QRect(120, 0, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.authorization_label.setFont(font)
        self.authorization_label.setObjectName("authorization_label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=AuthWindow)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 60, 284, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.login_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.login_layout.setContentsMargins(0, 0, 0, 0)
        self.login_layout.setObjectName("login_layout")
        self.login_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.login_label.setFont(font)
        self.login_label.setObjectName("login_label")
        self.login_layout.addWidget(self.login_label)
        self.login_lineEdit = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget)
        self.login_lineEdit.setObjectName("login_lineEdit")
        self.login_layout.addWidget(self.login_lineEdit)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=AuthWindow)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 150, 281, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.password_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.password_layout.setContentsMargins(0, 0, 0, 0)
        self.password_layout.setObjectName("password_layout")
        self.password_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.password_label.setFont(font)
        self.password_label.setObjectName("password_label")
        self.password_layout.addWidget(self.password_label)
        self.password_lineEdit = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget_2)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.password_layout.addWidget(self.password_lineEdit)
        self.error_label = QtWidgets.QLabel(parent=AuthWindow)
        self.error_label.setEnabled(True)
        self.error_label.setGeometry(QtCore.QRect(20, 240, 131, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.error_label.setFont(font)
        self.error_label.setObjectName("error_label")

        self.retranslateUi(AuthWindow)
        QtCore.QMetaObject.connectSlotsByName(AuthWindow)

    def retranslateUi(self, AuthWindow):
        _translate = QtCore.QCoreApplication.translate
        AuthWindow.setWindowTitle(_translate("AuthWindow", "Voice journal"))
        self.auth_button.setText(_translate("AuthWindow", "Авторизироваться"))
        self.exit_button.setText(_translate("AuthWindow", "Выйти"))
        self.authorization_label.setText(_translate("AuthWindow", "Авторизация"))
        self.login_label.setText(_translate("AuthWindow", "Логин"))
        self.password_label.setText(_translate("AuthWindow", "Пароль"))
        self.error_label.setText(_translate("AuthWindow", "Ошибка авторизации!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AuthWindow = QtWidgets.QDialog()
    ui = Ui_AuthWindow()
    ui.setupUi(AuthWindow)
    AuthWindow.show()
    sys.exit(app.exec())
