from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TreeWindow(object):
    def setupUi(self, TreeWindow):
        TreeWindow.setObjectName("TreeWindow")
        TreeWindow.setEnabled(True)
        TreeWindow.resize(1920, 1080)
        TreeWindow.setMaximumSize(QtCore.QSize(900, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ProgrammIcon.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        TreeWindow.setWindowIcon(icon)
        self.tableWidget = QtWidgets.QTableWidget(parent=TreeWindow)
        self.tableWidget.setGeometry(QtCore.QRect(430, 430, 881, 221))
        self.tableWidget.setMouseTracking(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        self.pushButton_2 = QtWidgets.QPushButton(parent=TreeWindow)
        self.pushButton_2.setGeometry(QtCore.QRect(1800, 1030, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=TreeWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 30, 160, 311))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.listWidget = QtWidgets.QListWidget(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.verticalLayout.addWidget(self.listWidget)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=TreeWindow)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(210, 30, 160, 114))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.label_2.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.listWidget_2 = QtWidgets.QListWidget(parent=self.verticalLayoutWidget_2)
        self.listWidget_2.setObjectName("listWidget_2")
        self.verticalLayout_2.addWidget(self.listWidget_2)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(parent=TreeWindow)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(400, 30, 160, 114))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.listWidget_3 = QtWidgets.QListWidget(parent=self.verticalLayoutWidget_3)
        self.listWidget_3.setObjectName("listWidget_3")
        self.verticalLayout_3.addWidget(self.listWidget_3)

        self.retranslateUi(TreeWindow)
        QtCore.QMetaObject.connectSlotsByName(TreeWindow)

    def retranslateUi(self, TreeWindow):
        _translate = QtCore.QCoreApplication.translate
        TreeWindow.setWindowTitle(_translate("TreeWindow", "Журнал преподавателя"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("TreeWindow", "Дам"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("TreeWindow", "Кармадонов"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("TreeWindow", "Лемешко"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("TreeWindow", "Пожидаев"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("TreeWindow", "Рязанов"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("TreeWindow", "Хмелёв"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("TreeWindow", "01.01.2023"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("TreeWindow", "02.01.2023"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("TreeWindow", "03.01.2023"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("TreeWindow", "03.01.2023"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("TreeWindow", "04.01.2023"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("TreeWindow", "05.01.2023"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("TreeWindow", "06.01.2023"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("TreeWindow", "07.01.2023"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("TreeWindow", "08.01.2023"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton_2.setText(_translate("TreeWindow", "Выйти"))
        self.label.setText(_translate("TreeWindow", "Факультет"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("TreeWindow", "ФАИТ"))
        item = self.listWidget.item(1)
        item.setText(_translate("TreeWindow", "ФЕНМиИТ"))
        item = self.listWidget.item(2)
        item.setText(_translate("TreeWindow", "ФКФН"))
        item = self.listWidget.item(3)
        item.setText(_translate("TreeWindow", "ИСИ"))
        item = self.listWidget.item(4)
        item.setText(_translate("TreeWindow", "ОМО"))
        item = self.listWidget.item(5)
        item.setText(_translate("TreeWindow", "ТЭФ"))
        item = self.listWidget.item(6)
        item.setText(_translate("TreeWindow", "ФПН"))
        item = self.listWidget.item(7)
        item.setText(_translate("TreeWindow", "ИСПТиК"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("TreeWindow", "Курс"))
        self.label_3.setText(_translate("TreeWindow", "Группа"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TreeWindow = QtWidgets.QDialog()
    ui = Ui_TreeWindow()
    ui.setupUi(TreeWindow)
    TreeWindow.show()
    sys.exit(app.exec())
