from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QApplication

class Ui_TreeWindow(object):
    def setupUi(self, TreeWindow):
        TreeWindow.setObjectName("TreeWindow")
        TreeWindow.resize(900, 300)
        TreeWindow.setMinimumSize(QtCore.QSize(900, 300))
        TreeWindow.setMaximumSize(QtCore.QSize(900, 300))
        self.tableWidget = QtWidgets.QTableWidget(TreeWindow)
        self.tableWidget.setGeometry(QtCore.QRect(10, 20, 881, 221))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.pushButton_2 = QtWidgets.QPushButton(TreeWindow)
        self.pushButton_2.clicked.connect(QApplication.instance().quit)
        self.pushButton_2.setGeometry(QtCore.QRect(800, 250, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(TreeWindow)
        QtCore.QMetaObject.connectSlotsByName(TreeWindow)

    def retranslateUi(self, TreeWindow):
        _translate = QtCore.QCoreApplication.translate
        TreeWindow.setWindowTitle(_translate("TreeWindow", "Журнал преподавателя"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("TreeWindow", "Дам"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("TreeWindow", "Кармадонов"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("TreeWindow", "Лемешко"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("TreeWindow", "Пожидаев"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("TreeWindow", "Рязанов"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("TreeWindow", "Хмелёв"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("TreeWindow", "01.01.2023"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("TreeWindow", "02.01.2023"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("TreeWindow", "03.01.2023"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("TreeWindow", "03.01.2023"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("TreeWindow", "04.01.2023"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("TreeWindow", "05.01.2023"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("TreeWindow", "06.01.2023"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("TreeWindow", "07.01.2023"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("TreeWindow", "08.01.2023"))
        self.pushButton_2.setText(_translate("TreeWindow", "Выйти"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TreeWindow = QtWidgets.QMainWindow()
    ui = Ui_TreeWindow()
    ui.setupUi(TreeWindow)
    TreeWindow.show()
    sys.exit(app.exec())